### ISSUE TITLE
Crash when adding to playlist (API 29 bug)

### ISSUE THREAD

**Issue by BumbleFlash** [CUTR-at-USF/MUSER#101]
**Describe the bug**
The app crashes when the user tries to add to the playlist using the overflow button on the Album, Song, or Artist. I can confirm this only happens in phones with API level 29 (possibly just Android 11). 

From this issue tracker over here, https://issuetracker.google.com/issues/147619577, looks like there's a bug in the external storage access for API 29 which still has not yet been fixed yet. I noticed this bug while I was working on capturing the favorite event. 

    Error adding to playlist
    Throwable: edu.usf.sas.pal.muser has no access to content://media/external_primary/audio/playlists/13648

MUSER automatically creates a Playlist Favorites while the user marks a song as a favorite. Although the song is being marked as a favorite, the song is not really added to the "Favorite" playlist due to the storage issue, instead throws the above exception. Note that, the app doesn't crash here. 

**To Reproduce**
1. Go to MUSER
2. Click on Overflow button (Vertical Triple dot)
3. Add to any Playlist

**Expected behavior**
The song should be added to playlist

**Observed behavior**
The app crashes

**Device and Android version:** 

Google Pixel 3a. Stock Android 11. Google Play Services 20.39.15

**Comment by barbeau** [comment]
Ugh. So looks like the issue has been fixed in AOSP but hasn't been rolled out to a lot of devices yet. Thanks for opening this and referencing the AOSP issue.

Could you try adding `android:requestLegacyExternalStorage="true"` as shown in the below commit in the manifest just to see if this changes anything? 

https://github.com/barbeau/gpstest/commit/7d13b5cea06159f2606e87590dff84dd3e1bcd45/

What Android build number/version on the Pixel 3a are you seeing the problem on? You can see this in the system "About" screen.

**Comment by BumbleFlash** [comment]
@barbeau My Pixel 3a's build number would be RP1A.201005.004.

**Comment by BumbleFlash** [comment]
@barbeau Update: Thank you for the link to the solution. It seems to have fixed the problem however, there are a few irregularities that I noticed while I was testing the app. We can discuss it in detail in our meeting and open an issue per our discussion?
