### ISSUE TITLE
The app seems to be inserting  the album names in place of the artist names.

### ISSUE THREAD

**Issue by pradeepsalunke** [CUTR-at-USF/MUSER#134]
**Describe the bug**
The data in artist names column is incorrect. 

**To Reproduce**
1. Go to firebase
2. Tap on cloud firestore
3. select any random user for e.g "2AzUudC1tyQMklupZFYSU0pyPw43"
3. Scroll down to ui-events
4. select ui-event id  "3-d331b2eb-ba8b-4fb7-bef1-454aa213b145"
4. Scroll down to song
5. check artist names
**Expected behavior**
artist names field should contain song artist name info.
<img width="446" alt="Screen Shot 2021-02-03 at 2 24 23 PM" src="https://user-images.githubusercontent.com/26131182/106798963-afdca800-662c-11eb-9ba7-275434cb5d2d.png">
<img width="508" alt="Screen Shot 2021-02-03 at 2 23 27 PM" src="https://user-images.githubusercontent.com/26131182/106798965-b0753e80-662c-11eb-9353-7624e0501f90.png">

**Observed behavior**
artist names field has album names info.

**Screenshots:**

**Comment by BumbleFlash** [comment]
@pradeepsalunke Could you please fill the template with the respective information so that we get a better understanding of what is going on? For example, please give a brief explanation about what the bug is in **Describe the bug** and so on. You don't have to attach the screenshots if you don't have any! Thanks

**Comment by BumbleFlash** [comment]
@pradeepsalunke Thanks for noticing this! I have opened a PR that fixes the problem. Look for the id prefixed with "k2qX" from  record number 4 to see the updated values from my test!
