### ISSUE TITLE
Stop playing music when the app is closed from the overview

### ISSUE THREAD

**Issue by BumbleFlash** [CUTR-at-USF/MUSER#8]
**Is your feature request related to a problem? Please describe.**
Shuttle continues to play the track after the user closes the app from the App overview. It'd be great if the track is paused or stopped when the user closes the app.

**Describe the solution you'd like**
The app should stop playing the music when the user kills the app from the App Overview section. The best way in my opinion to approach this is to change the state of the track that is currently playing to "Paused" while the app recognizes that is it is being killed.

**Comment by barbeau** [comment]
Good catch - I agree, when the activity is being destroyed it should try to pause the music (I'm assuming by communicating with the service, if that's what's playing the music).

**Comment by barbeau** [comment]
Actually, looking at his more, this is intended behavior that matches other music players like Google Play Music. Part of this is because you don't want the music to stop if the user hits the back button in the activity. To dismiss the notification you just need to pause the music and then you can swipe it away.
